#title: AVERtek # your name photo (or website title) here
logo1: "/images/Company Here.jpg?raw=true" # your photo (or logo) here
logo2: "/images/logo 1.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <b>ON MOBILE - View in Augmented Reality (AR):</b> <br>
    STEP 1- Press AR button below, place image in open space, anchor on surface, scale, view, walk-thru apartment  
  <br><br>
  <b>ON COMPUTER - View 3D Image Only:</b> <br>
    Use Pointer to rotate, spin; Use zoom to scale
  <br><br>
  <a href="https://avertek.net/gallery-images">STEP 2- View Actual Apartment Images</a> 
  <br><br>
  <a href="https://avertek.net/narrative">STEP 3- Take a Video Tour/Testimonials</a>  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
